// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPyNMexgEbg280-hvuKEJa3f6R3zAwD7Q',
    appId: '1:415353143568:web:5c20cf722e200393f2e595',
    messagingSenderId: '415353143568',
    projectId: 'flutter-challenge-2025',
    authDomain: 'flutter-challenge-2025.firebaseapp.com',
    storageBucket: 'flutter-challenge-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANdS5upyZA9cEaCFMcVSwfUTcx6XCTEMs',
    appId: '1:415353143568:android:85a99a24fd7fe704f2e595',
    messagingSenderId: '415353143568',
    projectId: 'flutter-challenge-2025',
    storageBucket: 'flutter-challenge-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZGGZNPxPxSn-L970otlIachdyYzoYoe0',
    appId: '1:415353143568:ios:411affb9d5035946f2e595',
    messagingSenderId: '415353143568',
    projectId: 'flutter-challenge-2025',
    storageBucket: 'flutter-challenge-2025.firebasestorage.app',
    iosBundleId: 'com.example.day15',
  );

}